# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VerificarUsuarioResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tipo_usuario: str=None):  # noqa: E501
        """VerificarUsuarioResponse - a model defined in Swagger

        :param tipo_usuario: The tipo_usuario of this VerificarUsuarioResponse.  # noqa: E501
        :type tipo_usuario: str
        """
        self.swagger_types = {
            'tipo_usuario': str
        }

        self.attribute_map = {
            'tipo_usuario': 'tipo_usuario'
        }
        self._tipo_usuario = tipo_usuario

    @classmethod
    def from_dict(cls, dikt) -> 'VerificarUsuarioResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VerificarUsuarioResponse of this VerificarUsuarioResponse.  # noqa: E501
        :rtype: VerificarUsuarioResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tipo_usuario(self) -> str:
        """Gets the tipo_usuario of this VerificarUsuarioResponse.


        :return: The tipo_usuario of this VerificarUsuarioResponse.
        :rtype: str
        """
        return self._tipo_usuario

    @tipo_usuario.setter
    def tipo_usuario(self, tipo_usuario: str):
        """Sets the tipo_usuario of this VerificarUsuarioResponse.


        :param tipo_usuario: The tipo_usuario of this VerificarUsuarioResponse.
        :type tipo_usuario: str
        """

        self._tipo_usuario = tipo_usuario
